---
title: "Restaurant Markdown"
author: "Chev Eldrid"
date: "April 7, 2019"
output: html_document
---

```{r setup, include=FALSE}
if (!require(tidyverse)) {install.packages("tidyverse")}
library(tidyverse)
library(readr)
library(ggplot2)
library(data.table)
```
Okay, we want to pull in the csv info...

..at this point the data has been massaged a bit to take out non-values

```{r}
fixed_data <- read_csv("unique-boston-rest.csv")
temp_fixed_data <- data.frame("PriceCount" = fixed_data$PriceCount, "Zip" = fixed_data$Zip)
#filtering for only Boston zips we have income data for
temp_fixed_data <- temp_fixed_data[temp_fixed_data$Zip %in% c("2151","2152","2129","2128","2113","2114","2203","2110","2109","2108","2111","2116","2210","2199","2115","2215","2118","2127","2120","2119","2125","2122","2121","2130","2131","2126","2136","2467","2135","2134","2163"), ]

avg_column <- aggregate(. ~ temp_fixed_data$Zip, temp_fixed_data[-2], median)
median_ratings <- data.frame("Zip" = avg_column$`temp_fixed_data$Zip`, "PriceCount" = avg_column$PriceCount)
write.csv(median_ratings, "zips-and-medians.csv")
ggplot(data = median_ratings, aes(x = median_ratings$Zip, y=median_ratings$PriceCount)) + geom_count()
```


Let's try and do something cool with the TYPES of food
```{r}
fixed_data <- read_csv("unique-boston-rest.csv")
split_cats <- data.frame(row.names = fixed_data[1, ])
#trying some freaky stuff
for(i in 1:nrow(fixed_data)) {
    row <- fixed_data[i,]
    categories <- strsplit(row$Category, ",")[[1]]
    for(j in 1:length(categories)) {
      rowTemp <- data.frame(row$Name, row$Rating, row$Price, row$PriceCount, categories[j], row$Lat, row$Long, row$City, row$Address, row$Zip)
      names(rowTemp)<-c("Name", "Rating", "Price", "PriceCount", "Category", "Lat", "Long", "City", "Address", "Zip")
      split_cats <- rbind(split_cats, rowTemp)
    }
    # do stuff with row
}
```
...I can't believe it worked.
Analyses based on avg price of restaurant categories
```{r}
#split_cats
skinned_cats <- data.frame("PriceCount" = split_cats$PriceCount, "Category" = split_cats$Category)
avg_column <- aggregate(. ~ skinned_cats$Category, skinned_cats[-2], mean)
freq_column <- data.frame(table(skinned_cats$Category))
freq_column <- data.frame("Category" = freq_column$Var1, "Count"=freq_column$Freq)
skinned_cats <- data.frame("Category" = avg_column$`skinned_cats$Category`, "PriceCount" = avg_column$PriceCount, "Mode" = freq_column$Count)
skinned_cats <- skinned_cats[skinned_cats$Mode > 1,]
cheapest_cats <- head(skinned_cats[order(skinned_cats$PriceCount,decreasing=FALSE),], n = 20)
skinned_cats <- head(skinned_cats[order(skinned_cats$PriceCount,decreasing=TRUE),], n = 20)
skinned_cats
cheapest_cats
```
Analysis based on avg rating of restuarant categories
```{r}
skinned_cats <- data.frame("Rating" = split_cats$Rating, "Category" = split_cats$Category)
avg_column <- aggregate(. ~ skinned_cats$Category, skinned_cats[-2], mean)
freq_column <- data.frame(table(skinned_cats$Category))
freq_column <- data.frame("Category" = freq_column$Var1, "Count"=freq_column$Freq)
skinned_cats <- data.frame("Category" = avg_column$`skinned_cats$Category`, "Rating" = avg_column$Rating, "Mode" = freq_column$Count)
skinned_cats <- skinned_cats[skinned_cats$Mode > 5,]
cheapest_cats <- head(skinned_cats[order(skinned_cats$Rating,decreasing=FALSE),], n = 30)
skinned_cats <- head(skinned_cats[order(skinned_cats$Rating,decreasing=TRUE),], n = 30)
skinned_cats
cheapest_cats

```
